import os
import argparse
import torch

here = os.path.dirname(os.path.abspath(__file__))
default_pretrained_model_path = os.path.join(here, '../pretrained_models/bert-base-chinese')
default_train_file = os.path.join(here, '../datasets/train')
default_validation_file = os.path.join(here, '../datasets/dev')
default_test_file = os.path.join(here, '../datasets/test')
default_radical_pretain_model_dir = os.path.join(here, '../radical_bert_model/')
default_output_dir= os.path.join(here, '../saved_models')
default_log_dir = os.path.join(default_output_dir, 'runs')
default_tagset_file = os.path.join(default_output_dir, 'tagset.txt')
default_model_file = os.path.join(default_output_dir, 'model.bin')
default_radical_model_file = os.path.join(default_radical_pretain_model_dir, 'pytorch_model.bin')
default_checkpoint_file = os.path.join(default_output_dir, 'checkpoint.json')
default_radical_config_file = os.path.join(default_radical_pretain_model_dir, 'config.json')
parser = argparse.ArgumentParser()

parser.add_argument("--pretrained_model_path", type=str, default=default_pretrained_model_path)
parser.add_argument("--train_file", type=str, default=default_train_file)
parser.add_argument("--validation_file", type=str, default=default_validation_file)
parser.add_argument("--test_file", type=str, default=default_test_file)
parser.add_argument("--output_dir", type=str, default=default_output_dir)
parser.add_argument("--log_dir", type=str, default=default_log_dir)
parser.add_argument("--tagset_file", type=str, default=default_tagset_file)
parser.add_argument("--model_file", type=str, default=default_model_file)
parser.add_argument("--checkpoint_file", type=str, default=default_checkpoint_file)
parser.add_argument("--radical_model_file", type=str, default=default_radical_model_file)
parser.add_argument("--radical_model_config_file", type=str, default=default_radical_config_file)
parser.add_argument("--radical_model_dir", type=str, default=default_radical_pretain_model_dir)

# model
parser.add_argument('--embedding_dim', type=int, default=768, required=False, help='embedding_dim')
parser.add_argument('--radical_embedding_dim', type=int, default=24, required=False, help='radical_embedding_dim')
parser.add_argument('--rnn_hidden_dim', type=int, default=256, required=False, help='rnn_hidden_dim')
parser.add_argument('--rnn_num_layers', type=int, default=1, required=False, help='rnn_num_layers')
parser.add_argument('--rnn_bidirectional', type=bool, default=True, required=False, help='rnn_bidirectional')
parser.add_argument('--dropout', type=float, default=0.1, required=False, help='dropout')

# parser.add_argument('--device', type=str, default='cpu')
parser.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu", help="Device (cuda or cpu)")
parser.add_argument("--seed", type=int, default=12345)
parser.add_argument("--max_len", type=int, default=200)
parser.add_argument("--train_batch_size", type=int, default=8)
parser.add_argument("--validation_batch_size", type=int, default=8)
parser.add_argument("--epochs", type=int, default=20)
parser.add_argument("--learning_rate", type=float, default=1e-5)
parser.add_argument("--weight_decay", type=float, default=0)

hparams = parser.parse_args()
